# Site settings
title: Star Relocations
email: info@starrelocations.com
description: Star Relocations is an employee relocation company specialising in professional tenants. We are based in Sussex and are always looking for new tenants, landlords and letting agents to work with us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.starrelocations.co.uk"
jumbotron_1: Let your property to <b>Star Relocation Services</b>
jumbotron_2: for a <b>hassle free</b> and <b>profitable</b> tenancy
banner_src: /images/banner.png
phone: 01273 917 789

# Build settings
markdown: kramdown
